### ISSUE TITLE
一部のルールがシリアライズされない

### ISSUE THREAD

**Issue by Yodokoro** [enue/TSKT_Mahjong#1]
こんにちは。良さそうなライブラリだったので使ってみました。
一点困った点があったので連絡させていただきました。

# 再現手順
①Game.Create()で新しいゲームを作成する。
　このときEndRuleで既定値以外の値を指定する(lengthType = LengthType.半荘戦 など)。
　また、PaymentRuleでも既定値以外の値を指定する(ウマ = new[] { 30, 10, -10, -30 }など)
②ゲームをSerializeSession().ToJson()でJsonにシリアライズする
③シリアライズされたJsonをTSKT.Mahjongs.Serializables.Session.FromJson()で復元する

# 現象
Round.game.rule.end及びRound.game.rule.paymentが既定値になっている。

# 期待動作
ルールがシリアライズする前の値に復元されている。

# 備考
EndRule、PaymentRuleに[System.Serializable]アトリビュートを付ければ解決するものと思われます。
私の仕様の勘違いでしたらすみません。
もしよければご対応よろしくお願いします。

**Comment by enue** [comment]
https://github.com/enue/TSKT_Mahjong/commit/ea3de341116a5d5af164a77807f299c3b9a02e2a
ありがとうございます！

**Comment by Yodokoro** [comment]
迅速なご対応誠にありがとうございます！　助かりました。
